enum eMESSAGE_TYPE
{
    TO_WALK,
    TO_IDLE,
    TO_RUN,
    TO_ATTACK,
    TO_DIE,
    TO_HIT,
    TO_BATTLEIDLE,
    TO_BATTLEWALK,
    FIND_ENEMY,
    ATTACKABLE,
    ROLLINGABLE,
    FLLOW_ME,
    SET_FOMATION,
    REMOVE_AND_DROP,
}